### ISSUE TITLE
"Failed creating directory"

### ISSUE THREAD

**Issue by jh4892** [shiftpi/nextcloud-chunk-file-upload#18]
After a few days of testing different Nextcloud npm modules for uploading large files (>512MB), this module seems to be the only one that works, nice job! 

But it only works when I upload the file to the root-folder, else it says "Failed creating directory".

( Perhaps you are better of using the native Webdav solutions, like mapping a networkdrive on Windows: https://docs.nextcloud.com/server/24/user_manual/en/files/access_webdav.html )

**Comment by shiftpi** [comment]
@jh4892 Thanks for reporting.
You're right, uploading to a sub directory wasn't possible till now. The reason for this was, that the uploader tried to create the whole sub directory structure also for the chunk-containing directory.
However this is not necessary at all.

I released package version v1.1.0 containing a fix.
